name: Run Go Program and Package Artifacts

on:
  workflow_dispatch: # 手动触发

jobs:
  run_and_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2
      - name: Run Go Program
        run: go run main.go
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: repo-backup
          path: ${{ github.workspace }}
          compression-level: 9 # maximum compression